names = [
        'Pickle Snatcher',
        'Merlin',
        'Gandalf',
        'Dumbledore',
        'Dobby',
        'Smeagol',
        'Argle Bargle',
        'Fuchi',
        'Turdberg',
        'Shrek',
        'T-Gob',
        'King Harkinian',
        'Parn',
        'Deedlit',
        'Tingle',
        'Pyrotess',
        'Grimace',
        'Hamburglar',
        'Burger King King',
        'Krinkles the Clown',
        'Beauford',
        'Cletus',
        'Jebus',
        'Cheesus',
        'Gumby',
        'Mario',
        'Luigi',
        'Wario',
        'Waluigi',
        'Moonman',
        'Mr Clean'
        'Shit Widgit',
        'Fat Albert',
        'Scooby Doo',
        'Mr Skeltal',
        'Dildo Scumbaggins',
        'Hairy Twatter',
        'Captain Planet',
        'Professor Gape',
        'Skeletor',
        'Cobra Commander',
        'Random Ninja',
        'Larry the Cable Guy',
        'Paul Blart',
        'Robocop',
        'Judge Dredd',
        'Rambo',
        'Chuck Norris',
        'Ash Williams',
        'Daring Dragoon',
        'The Noid',
        'Meineke German',
        'Shredder',
        'Leonardo',
        'Donatello',
        'Michaelangelo',
        'Raphael',
        'Splinter',
        'April O\'Neil',
        'Gay Splinter',
        'Scruff McGruff',
        'Louie the Lightning Bug',
        'Inspector Gadget',
        'Bob Ross',
        'Mr Rogers',
        'Captain Kangaroo',
        'Cap\'n Crunch',
        'Count Chocula',
        'Peter Pan',
        'Captain Hook',
        'Captain Picard',
        'Captain Kirk',
        'Spock',
        'Data',
        'Warf',
        'Speed Racer',
        'Green Ranger',
        'Black Ranger',
        'Pink Ranger',
        'White Ranger',
        'Blue Ranger',
        'Red Ranger',
        'Fred Sanford',
        'Papa Smurf',
        'Garagamel',
        'Frasier',
        'McGuiver',
        'Pricess Tomato',
        'Sir Cucumber',
        'Percy',
        'Nightman',
        'Link',
        'Zelda',
        'Street Shark',
        'Foot Soldier',
        'Turbo Teen',
        'Robbie Rotten',
        'Sporticus',
        'Blippy',
        'Pinkfong',
        'Scrubbing Bubble',
        'Toilet Duck',
        'Pillsbury Doughboy',
        'Hamburger Helper Glove',
        'Green Giant',
        'Scrote',
        'Brisco County Jr'
        'Michael Knight',
        'Roscoe P Coltrane',
        'Daisy Duke',
        'Rocksteady',
        'Bebop',
    ]